### ISSUE TITLE
[Bug] Myself page losing wiki links after search 

### ISSUE THREAD

**Issue by umbralOptimatum** [alanhuang122/fl-oneclick-wiki#20]
1. Search for a quality, say, Repeat Dentistry.
2. The desired quality appears and its image is correctly linked via one-click wiki, like so:

<img alt="Screen Shot 2023-08-14 at 5 50 53 PM" src="https://github.com/alanhuang122/fl-oneclick-wiki/assets/12092270/e660b72e-a5ca-4fe7-9b9e-d6df0fc1b2ab">

3. Clear the search.
4. Quality images in categories not present in the search results correctly link to the wiki. Qualities that did not match the search but are in the same category as qualities that did match are missing their wiki links.

Straightforward cause, hopefully a straightforward fix.

**Comment by lensvol** [comment]
I replicated this bug, will be fixed when https://github.com/alanhuang122/fl-oneclick-wiki/pull/21 gets merged.
